name: Verify Build

on:
    push:
        branches-ignore:
            - master
    pull_request:
    workflow_dispatch:

jobs:
    verification:
        name: Verification
        runs-on: ubuntu-latest
        steps:
            -   name: Check out project
                uses: actions/checkout@v2
            -   name: Set up JDK 6
                uses: actions/setup-java@v1
                with:
                    java-version: '6.0.119'
                    java-package: jdk
                    architecture: x64
            -   name: Set up JDK 8
                uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
            -   name: Build and bundle plugin artifact
                run: ./gradlew clean build -Porg.gradle.java.installations.fromEnv=JAVA_HOME_6_0_119_X64 -PjavaCompilerVersion=6 -Pteamcity-build-scan-plugin.acceptGradleTOS=true
                env:
                    GRADLE_ENTERPRISE_TEST_INSTANCE: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN != null && 'https://ge.solutions-team.gradle.com' || '' }}
                    GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN != null && secrets.GE_SOLUTIONS_ACCESS_TOKEN || 'dummy.server=dummy_value' }}
