name: "Release Gradle project"
on: [ workflow_dispatch ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out project
                uses: actions/checkout@v2
            -   name: Set up JDK 6
                uses: actions/setup-java@v1
                with:
                    java-version: '6.0.119'
                    java-package: jdk
                    architecture: x64
            -   name: Set up JDK 8
                uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Build and bundle plugin artifact
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: clean build publishPlugin -PRELEASE -Porg.gradle.java.installations.fromEnv=JAVA_HOME_6_0_119_X64 -PjavaCompilerVersion=6 -Pteamcity-build-scan-plugin.acceptGradleTOS=true
            -   name: Upload plugin artifact
                uses: actions/upload-artifact@v3
                with:
                    name: teamcity-build-scan-plugin
                    path: build/distributions/teamcity-build-scan-plugin-*.zip
