name: "Build Gradle project"
on: [ push, workflow_dispatch ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out project
                uses: actions/checkout@v2
            -   name: Set up JDK 8
                uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Build and bundle plugin artifact
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: build -Pteamcity-build-scan-plugin.acceptGradleTOS=true
            -   name: Upload plugin artifact
                uses: actions/upload-artifact@v3
                with:
                    name: teamcity-build-scan-plugin
                    path: build/distributions/teamcity-build-scan-plugin-*.zip
