name: "Build Gradle project"
on: [ push, workflow_dispatch ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out project
                uses: actions/checkout@v2
            -   name: Set up JDK 8
                uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Build with Gradle
                uses: gradle/gradle-build-action@v1
                with:
                    arguments: build -Pteamcity-build-scan-plugin.acceptGradleTOS=true
                    distributions-cache-enabled: true
                    dependencies-cache-enabled: true
                    configuration-cache-enabled: false
